CREATE TABLE 
users (
	uuid VARCHAR PRIMARY KEY NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	active INTEGER DEFAULT 0 NOT NULL,
	otp INTEGER NOT NULL
);

CREATE TABLE 
